language: node_js
sudo: false
node_js:
- '6'
after_success: "./script/push"
services:
- docker
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  global:
  - secure: FFcYVqYlZv4NoWZReC6FEJ/49AWJv4eD2lKEws+EwXSGD3v9F88XnnQ/A1u4LK6GWMuH9i0AEEQBP0k8XC0FjC6IIJ5Y2X1sbdewyAJUxg+NXlAm8RU7lzUf6hBtOhtlSXdlooAf0lFKBMSzKXn0WC3afaUkTf9j43tkotHW8q5hHygGu8O9EzorJ8mDYzWiayDck4dedpz8Gcb70IZZvw5PFuChxf++THFK5NHOrWe0Hy5QJcyfyujogEJbo+vKzNZ2STDqCugXSD60Q4qxd+i4hx/JwHKsMd/6gzLlismsjYvlTVoufl+RFrspkaXciNtt7ofvHPJMQWwYvoKjUqZETq5L2gfpD02wvProGAQYebt3ivq+wUAdAUfHNVORRNvB1xmorRBeK3atCWBWiKm0r2j4h8xkqc8IGFN9iv20We6ncLghqLTv6iY3SVkeRrKCZ2jrT1NwoAI90p6hDz5eJQcQpImFxkkCFjOf7e6EKGvIQxo4E2UaPeIW0gWVvgCDNG/DVqDKaCah6NHnfo5+eS+k070aWIW9D38aA1SMHuvmC93KRMhod/nTHkonmQwLbnXPTCtUMoeWgeltrk57dO3KxBtYv4AS3c6a1SYtYqazlwjtz4uQdYDS8Ny4l3pAkumxfLJB4mFGUgsnP7/YEJnLh7MahdbzZuqP+Yk=
  - secure: OoUFVV8NWFKzi9BTd/kBLoL8RWidxwokQvsv8nGwI2v+1zFMNOdyUSQK4pawAkN9bI42UKeoVGTOmkUIEDsyfrcCyYGGzy7QJ7pbwexEw5chUiGO7Wsnep/iaesR1Wboqtnsg+SSVWbyr9tH+dB3f0pmS0OOReCMibPQtiD10lFtYicDNHd8Qm74Xea4xfTDHz1MVz/hPQ7l34UE5XJNMq3hxYhS1NS356+dgdx08RhWqK/z80HDEKGBcoLUGV7MqZVyy52Nb78wmnvcOpKznR/qZtEVkBD7LEQqKjSHs1xzFWGHKwBm25JHnAOhdDACxImJVSXmNX/NGNQHFORBBhAx/iOCDFiHbmN4HFr+CS8O/GqxgffpkSn2XX8AEPVfwBWfYZ6rTk9PwqKIjuUatKwt8xs1dM74KjXZyZy7daBU75/qI4iCM9F3Q07COqkR/IbYYa1rrlwXBUmpdbLYOkuzh9x2nxYFaTI2cPAwRotjl48rGVfFKKpMbid+dkjgKBp1dpQK8UzX0162TMMX6fp5tqcOzJTTvFPspPh6DzB/7jbfbR74wGJUf1sHUNeGC5W8FdmN1KXFojLver7KNkyA3sRwrK7SeDuuKnEU2mgJlcOBgn5688st18QSYEBItww8NXCqRwW5wRh9H6km7O+Y7ps26wdHCMvigNBfZOo=
