language: node_js
sudo: false
node_js:
- '6'
after_success: "./script/push"
services:
- docker
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  global:
  - secure: eJs3xOKesxHrTfFCL4riqHuGpedt+drCLdLc85tRuzhp2RuqMoRbFkQ4SqDe4c6U3GsBn7g5a3Pa2b4DmSSaVoK/e8q1t9pXPOanrgJvWwceMfDPZNpsI2pJta6DfUkGKa2MRB6Sf0aHeaqFwX43Zn3f4xRHwxDKPlBM3g2UYJ+gOUWfjUwpD9sSXPRWmza+XztdQrWJk1nctiDZn+ytFyztLJ3CeogBPXoEhyHrFjh4b6/4Fgj3QULhMXTrcpqO7mdHpsVbKSNOWdsNK0NTsLdQkA0U052mbKZMeptmEPDetynH/wf1An2T0Q8qVLQ6y4phaLQF87isbVhx/piwygWcaxCCGMZ3Rv5RmCP0qJfZyGm8Y0n5cPzeQ38I/0Wyz/7y7sY2Bslo4OgY05jw+yTD1sUnN/pdq+jP7E/O1ksLo2HkmJehIIshPEa662G2AAY2uS1Nrl/2rZ+4Tb1xk9zOkZ1o66PrguSrdjEbUZczZgOFuoSWxefW9tFxdnJjC40/Cm7KNmUrCpa0+KxsfiWhSinYMx3hpXJYfftf390QuYbj14r7oWqiXQSR+fTgNycZzhTEh/W/mW2Tik+CIReKGD7uCjiMKI1N5VslHHxsbe5VNJ+l67D8iplmn80Qyv4U9W3CK08TP7ptc/Xvkq3eyNhGbpiHiZ0i3X9vl9o=
  - secure: ecgILkG085Mmm6/VxnkXpQ6EmziX2Vursh5lvNDc8Hjkd8iYKz1z49h86SJ1NM4LftQWjYEI+7EvpZoUefXW0AOUYkpAZoBC+iM+AkzpbZlPZWhgf4trpTMzQnf/Kp6B5/527bIzDPXfzwEMXXR+giG3/ipZsLUt5rK1jJsUNI3irAYt/WCB72w0XMJNVW3h788aTN45647snwmWQfkTuDBm3C9Ce1QRvcD88Ef0zmvE8Exsvrh+MnA/p3WWyFc3f7M47811/rwyvF55Z25uAP1G7mrGqOADhmgN3smCC75CH7GaPiZvgLzIn9Ev/BwvLiy7B7g6vrE19y/N0IyHoqzfvrUKb6R0f11A7MMOupXOwgSS6EfUND/ZuvEPrtxfZrfYRsgIzcgd1knaD6V622/lOwVJKihixIKsfMpUS12LnFmnhZe4tLEpQrHiYO59utEo1+lKLTYKg7P1aOwj788gOvo567GPvUURe84Zd1YWqV1mxCIjzxZ8GopiFjRZoP2yCm2SeEy7WnD0J2gk6oexWOAz261TV70QBlkx8wWn0UET12Oe9sBWrjZKFj7BKNj47cqSbvj1Rv46CDPr0YibxbNXGZv2hK6g4kRvUwAQr6JDC7bDbctyAubaGiwH85JeIKqcl9iXfOlKA8AvNY1zfwUBBk3ktif8uq0/k5s=
